### ISSUE TITLE
Opens from Trent

### ISSUE THREAD

**Issue by pwojnaro** [planship/planship-docs#2]
**1. Example for metered lever aggregation formula options (especially unique buckets)** 
pwojnaro will provide

**2. Example for metered lever scope**
pwojnaro will provide

**3. Plans - use-calendar - what does it mean if false?**
This no longer exists, remove

**4. Plans - subscriber limit vs seat lever?**
Please clarify - are you asking what term should we be using?

**5. main-api - remove?**
Talking about the API reference? We can remove for now, but I think we should have this + some guide on how to generate your own client from the API spec.

**6. integration-customers - add additional line to code blocks accessing customer ID**

**7. integration-entitlements - what if i want to show you the maximum of a thing they’re entitled to (e.g. 120 minutes used of 200) - maybe just mention that this can be done and link to the usage docs where you get info for a specific metering id?**
the limits can be retrieved by retrieving plan details (along with all entitlements). I don't currently have that documented, but it's in the SDK

**8. integration-entitlements - multi subscription logic example (something like if plan a specifies x and plan b specifies y, then y will be used because it’s bigger)**
Yeah, we can have an example for this.

**9. integration-subscription - add example return values**
Can do

**10. integration-frontend - remove?**
Yeah, I think all of this is covered by the integration guide now.

**Comment by trentpeterson** [comment]
I believe we've addressed all of these at this point.
